### ISSUE TITLE
멘토링 사전 질문

### ISSUE THREAD

**Issue by worldone-web** [worldone-web/Team4-Traveler#6]
2.체류 시간
장점: 체류 시간이 오래 있을수록 그만큼 관광지에 대해 관심이 있다는 증거이다.
단점: 하지만 각 관광지마다 즐기는 시간이 다르므로 객관적인 지표가 될 수 없다.

3.mbti
장점: 선호도라고 생각될 수 있는게 자신이 생각하는 자신의 모습이므로 반영해볼 여지가 있다. 사용자의 질의도 단순화 시킬 수 있다.( i,e)로 분류하여 사람이 많은곳 적은곳 구분하여
데이터 셋 분류함.
단점:  실제로 자신이 생각하는 자신이 아닐수도 있다. 개인의 성향이 환경에 따라 변할 수 있으므로 판단의 근거가 어렵다 

4.소피패턴
장점: 사람이 돈을 잃다거에서는 민감하므로  많이 사용할 수록 그 관광지의 가치를 높게 평가하므로 개관적인 지표가 된다.
단점: 모델 훈련을 위한 데이터 수집이 불가하다. 구매 기록은 사용자의 민감한 개인 정보로 추천 모델을 만들기 위한 데이터 수집이 어려운 문제가 있었다. 

5.시즌제
장점: 사용자의 1년 계획에 맞춰서 전체 관광지 추천을 할 수 있다.
단점:  이미 정해진 관광지를 추천해서 개인화라고 하기에는 부족하다. 

6.숨은명소(brainstarming)
장점: 부산의 알려지지 않은 매력을 알릴 수 있고 유명도에 가려져 선호도가 무시되는 경향을 해결할 수 있다.
단점: 개인화라고 보기에는 부족하다. 

7.관광지 방문순서
장점: 사용의 개인 선호도를 간접적으로 수집할 수 있습니다.
단점: 거리기반으로 만들었을 경우 평향된 결과가 나타날 수 도 있습니다.

#공부 방향성
데이터 셋 확보( tripadviese로 크롤링)하기 ->  딥러닝을 통해서 공부해서 모델 만들기 ->  precision and recall 방법으로 모델 평가 ->  웹/앱 제작 및 배포

**Comment by hashilyze** [comment]
Q. 문제 정의서에 따르면 이 프로젝트의 결과물을 "개인화된 위치 기반 추천 시스템"으로 보입니다. 유사한 기술/서비스에 대해 조사해 보면, foursqure, tripadvisor 등의 기존의 서비스와 차이가 있다고 보기 어렵습니다.
그렇기에, 추천 서비스가 기존과 차별화를 주기 위한 시도가 필요하다고 봅니다. 이런 이유로 위와 같은 아이디어를 생각해 보았습니다.
기존의 서비스와 차별화된 서비스를 적용시키려는 것에 대해 어떻게 생각하십니까?

**Comment by worldone-web** [comment]
Q. POI을 위해서 딥러닝 기술이 매우 중요할 거 같습니다. 그래서 저희가 조사해본 결과 넷플릭스, 왓챠, 카카오 등 다양한 기업에서
협업 기반 필터링 및 컨텐츠 기반 필터링을 주로 이용하는 것을 알아보았습니다. 그중에서 저희는 초기 유저의 데이터 셋이 없어도
추천할 수 있는 협업 기반 필터링을 이용하고자 합니다. 협업 기반 필터링 통해서 딥러닝을 구축할려고 하는데 저희 프로젝트
방향성이 일치하는지 확인 하고 싶습니다.

**Comment by hashilyze** [comment]
Q. 추천 시스템은 제작 후, 그 품질을 평가할 필요가 있습니다. 추천 시스템이 우수하다는 것을 보이려면 모델의 정확도가 높다는 것 외 다른 지표가 필요하다고 봅니다. 
이를 위해 "협업 기반 필터링을 사용한 모델보다 정확도가 높다", "tripadvisor와 같은 기존의 서비스가 추천하는 장소와 우리가 만든 시스템의 추천하는 장소가 유사한가"와 같은 방법을 생각하고 있습니다.
추천 시스템을 검증하는 위와 같은 방법이 올바른 방법이라고 볼 수 있습니까?

**Comment by worldone-web** [comment]
Q. 협업 기반 필터링을 통해 딥러닝을 하고자 할 때 보통 행렬 인수분해를 통해 사용자- 아이템 선형구조를 표현한다 되어 있는데 이와 유사해 보이는 모델이 NCF라고 하던데 NCF도 협업 기반 필터링 처럼 "일반화 행렬 인수분해"와  "다층 퍼셉트론"을
통해 모델을 개발한다고 하는데 NCF가 협업기반 필터링이 맞는지 궁금합니다

**Comment by replica123** [comment]
여러가지 데이터셋 타입중에 개인화에서의 서로 유사성이 높은  칼럼들을 얼마나 뽑아야되는지
